tippy('#personal-phd', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>The personal PhD</h1><hr/><em>Last updated 2019-07-16</em><hr/><p>Lots of people aspire to do a “personal master’s degree,” but I’ve never seen anyone describe an attempt to do a “personal PhD.” With the caveat that I haven’t done a PhD myself, it appears to me that many components of it are achievable outside a traditional program. I think people who are drawn to PhD programs should consider whether they can assemble the key ingredients on their own.</p><p>As far as I can tell, these are the key ingredients:</p><ol><li>A broad understanding of the history and methods of your discipline, and a deep, constantly renewing understanding of a specialty within that discipline.</li><li>Several peer-reviewed publications.</li><li>Frequent feedback from an expert mentor over a period of several years.</li><li>Extensive experience teaching and evaluating beginners.</li><li>Completion and publication of a large research project that makes an original contribution.</li></ol><p>None of these things are easy to do outside a PhD program, but they’re all possible. You can learn independently: materials are abundant and usually free, so in many disciplines the only barriers to understanding are time and discipline. You can publish papers in industry journals or conference proceedings. You can find an expert mentor. You can volunteer to lead workshops, or find a part-time teaching position. And as long as you can acquire the tools and the data, you can do original research.</p><p>Of course, people consider doing PhDs for different reasons. Different end-goals may call for different mixtures of ingredients. But if you’re considering one at all, it’s worth asking yourself: for whichever parts of the experience are most appealing to you, is there a DIY version that might be just as good?</p></div>'
});