tippy('#about-me', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>About me</h1><h2 id="whats-my-story">What’s my story?</h2><p>I grew up in Peterborough, Ontario. It was a wonderful and fortunate childhood, filled with fantasy novels, James Taylor albums, canoe trips, and swim meets.</p><p>I studied everything and nothing in McMaster University’s interdisciplinary <a class="external-link" href="https://en.wikipedia.org/wiki/McMaster_Arts_and_Science" target="_self">Arts &amp; Science program</a>, where I found my people.</p><p>After a year of teaching writing at a Niagara College in Welland, Ontario, I decided to train as a data scientist. I moved to the west coast to study in the first cohort of the <a class="external-link" href="https://masterdatascience.ubc.ca/" target="_self">Master of Data Science program</a> at the University of British Columbia.</p><p>I now live in Vancouver with my partner. I love listening to music, playing chess, bouldering with friends, and biking everywhere no matter how hard it’s raining.</p><h2 id="what-do-i-do-for-work">What do I do for work?</h2><p>I’m a senior data scientist at <a class="external-link" href="https://imbellus.com/" target="_self">Imbellus</a>, an LA-based startup that makes simulation-based cognitive assessments, for use by employers and educators.</p><p>I write scoring logic, develop predictive models of hiring outcomes, and do analyses to inform assessment designs. I also present to clients, interview candidates for our growing team, and collaborate with psychometricians, learning scientists, game designers, AI researchers, and engineers.</p><p>See this <a class="external-link" href="https://www.bloomberg.com/news/features/2019-03-19/a-harvard-dropout-s-plan-to-fix-college-admissions-with-video-games" target="_self">Bloomberg article</a> to learn more about the company, or watch our CEO Rebecca Kantar’s <a class="external-link" href="https://www.youtube.com/watch?v=JoTlMNamSAg" target="_self">talk at Google</a>.</p><h2 id="how-should-you-contact-me">How should you contact me?</h2><p>The best way is to send me a message on <a class="external-link" href="https://twitter.com/davidklaing" target="_self">Twitter</a>. You’re also welcome to email me at davidkendalllaing at gmail dot com.</p><h2 id="why-should-you-contact-me">Why should you contact me?</h2><p>Because then we might become friends! Perhaps you…</p><ul><li>know of something that I might find interesting.</li><li>read something on my site that <em>you</em> found interesting.</li><li>want to collaborate on a project.</li><li>want to meet me for coffee.</li></ul></div>'
});