tippy('#bookshelf-loved', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Loved</h1><ul><li>Bach, <em>Jonathan Livingston Seagull</em> (1970)</li><li>Barron, <em>The Lost Years of Merlin Saga</em> (2000)</li><li>Card, <em>Ender’s Shadow</em> (1999)</li><li>Card, <em>Ender’s Saga</em> (1996)</li><li>Carnegie, <em>How to Win Friends and Influence People</em> (1936)</li><li>Caro, <em>The Path to Power</em> (1982)</li><li>Chabon, <em>The Amazing Adventures of Kavalier &amp; Clay</em> (2000)</li><li>Chiang, <em>Exhalation: Stories</em> (2019)</li><li>Christian, <em>Algorithms to Live By</em> (2016)</li><li>Forster, <em>The Machine Stops</em> (1909)</li><li>Frank, <em>The Diary of a Young Girl</em> (1947)</li><li>Gaiman, <em>The Ocean at the End of the Lane</em> (2013)</li><li>Gibson &amp; Sterling, <em>The Difference Engine</em> (1990)</li><li>Gleick, <em>Isaac Newton</em> (2003)</li><li>Gleick, <em>The Information</em> (2011)</li><li>Golding, <em>Lord of the Flies</em> (1954)</li><li>Gowdy, <em>Disneyland</em> (1989)</li><li>Haidt, <em>The Righteous Mind</em> (2012)</li><li>Haidt, <em>The Happiness Hypothesis</em> (2005)</li><li>Harris, <em>Free Will</em> (2012)</li><li>Harris, <em>Waking Up</em> (2014)</li><li>Hawley, <em>Before the Fall</em> (2016)</li><li>Hofstadter, <em>Gödel, Escher, Bach</em> (1979)</li><li>Irving, <em>A Prayer for Owen Meany</em> (1989)</li><li>Joyce, <em>Araby</em> (1914)</li><li>Joyce, <em>The Dead</em> (1914)</li><li>King, <em>On {Writing}</em> (2000)</li><li>Martel, <em>Life of Pi</em> (2001)</li><li>McCarthy, <em>The Road</em> (2006)</li><li>McMurtry, <em>Lonesome Dove</em> (1985)</li><li>Miller, <em>Know My Name</em> (2019)</li><li>Nielsen, <em>Reinventing Discovery</em> (2011)</li><li>Nimmo, <em>Children of the Red King 1-5</em> (2002-2006)</li><li>Pinker, <em>How the Mind Works</em> (1997)</li><li>Pinker, <em>The Language Instinct</em> (1994)</li><li>Pinker, <em>The Sense of Style</em> (2014)</li><li>Pullman, <em>His Dark Materials</em> (2000)</li><li>Rowling, <em>Harry Potter 1-7</em> (2007)</li><li>Thiel, <em>Zero to One</em> (2014)</li><li>Wallace, <em>Oblivion</em> (2004)</li><li>Wallace, <em>Infinite Jest</em> (1996)</li><li>Wallace, <em>Both Flesh and Not: Essays</em> (2012)</li><li>Watterson, <em>Calvin and Hobbes</em> (1985-1995)</li><li>Westover, <em>Educated</em> (2018)</li><li>Wickham, <em>Advanced R</em> (2014)</li><li>Yudkowsky, <em>Rationality From AI to Zombies</em> (2015)</li><li>Yudkowsky, <em>Harry Potter and the Methods of Rationality</em> (2015)</li></ul></div>'
});