tippy('#chess-tactics', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Chess tactics</h1><p>1. If your opponent exposes their queen in the opening, trade queens with them to prevent them from castling. (It took me SO LONG to understand why people kept doing that to me.)</p><p align="center"><img src="/assets/img/chess/trade_queens.png" width="70%"/></p><p>2. Two pawns on the sixth rank is worth at least a rook. In the position below, white is going to dominate.</p><p align="center"><img src="/assets/img/chess/two_pawns_worth_a_rook.png" width="70%"/></p><p>3. Look for forks. A fork is a move that attacks two pieces simultaneously. In the position below, white’s knight attacks black’s bishop and rook at the same time.</p><p align="center"><img src="/assets/img/chess/forks.png" width="70%"/></p><p>4. Look for pins. A pin is a move that traps a valuable piece behind a less valuable one. In the position below, black’s G pawn is “pinned”. It can’t advance or capture the queen because white’s bishop is x-raying black’s king.</p><p align="center"><img src="/assets/img/chess/pins.png" width="70%"/></p><p>5. Look for skewers. A skewer is a move that forces a valuable piece to move out of the way, allowing the capture of a less valuable piece. In the position below, black has skewered white’s king, allowing black to capture white’s queen.</p><p align="center"><img src="/assets/img/chess/skewers.png" width="70%"/></p><p>6. In a queen-only checkmate, back your opponent’s king into a corner by successively moving your queen so that it is a knight’s-move away from their king. Then bring your king over to support your queen in the checkmate.</p><p align="center"><img src="/assets/img/chess/queen_checkmate.png" width="90%"/></p><p>7. In a two-rook checkmate, roll their king across the board one rank or file at a time.</p><p align="center"><img src="/assets/img/chess/two_rook_checkmate.png" width="90%"/></p></div>'
});